name: Action for features branches
on: 
  push:
    branches: 
      - "!main"
      - "**"
jobs:
  Practice-build:
    runs-on: ubuntu-latest
    steps:
    - name: check if file exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: ".editorconfig"
        fail: true

  Linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - run: pip install pylint && pip install pylint[spelling]
    
    - name: Codelint with pylint and black
      run: pylint ./
