name: Action for features branches
on: 
  push:
    branches:
      - "!main"
jobs:
  Practice-build:
    runs-on: ubuntu-latest
    steps:
    - name: check if file exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: ".editorconfig"
        fail: true
    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      run: echo "It exists !"