name: Action for features branches
on: 
  push:
    branches: 
      - "!main"
      - "**"
jobs:
  Practice-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "./app"
          options: "--check --verbose"
